import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Field, Select } from "../verification/PredicateEditor";
import { evaluationsApi, type Snapshot, type Status } from "../../api/evaluations";

export const measurement = (value: number | null, suffix = "") => value === null ? "Unavailable" : `${value.toLocaleString(undefined, { maximumFractionDigits: 6 })}${suffix}`;
export function Verdict({ status }: { status: Status | null }) { return <span className="text-xs font-semibold" style={{ color: status === "pass" ? "var(--rp-success)" : status === "fail" ? "var(--rp-danger)" : "var(--rp-warning)" }}>{status === "pass" ? "Pass" : status === "fail" ? "Fail" : status === "inconclusive" ? "Inconclusive" : "Pending"}</span>; }
export function ResponseSpanSelect({ runId, value, onChange, label = "Response span (optional)" }: { runId: string; value: string; onChange: (value: string) => void; label?: string }) {
  const spans = useQuery({ queryKey: ["evaluation-response-spans", runId], queryFn: () => evaluationsApi.responseSpans(runId), enabled: !!runId });
  return <Field label={label} hint={spans.isError ? spans.error?.message ?? "Response spans could not load. Open the trace to inspect it." : spans.data?.truncated ? "Some response choices or names were omitted or redacted because captured metadata was unavailable." : "Automatic selection uses the agent response; choose explicitly if the trace has ambiguous output."}><Select value={value} onChange={event => onChange(event.target.value)} disabled={!runId || spans.isLoading}><option value="">Automatic response selection</option>{spans.data?.spans.map(span => <option key={span.id} value={span.id}>{span.name} · {span.spanType}</option>)}</Select></Field>;
}
export function SnapshotPreview({ snapshot, title = "Source snapshot" }: { snapshot: Snapshot; title?: string }) {
  const metrics = snapshot.metrics;
  return <section aria-label={title} className="space-y-3 rounded-md border border-[color:var(--rp-border)] p-3 text-xs">
    <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{title}</h3><span>{snapshot.complete ? "Complete captured trace" : "Incomplete captured trace"}</span></div>
    {(snapshot.redacted || snapshot.truncated) && <p className="text-[color:var(--rp-warning)]">{snapshot.redacted ? "Sensitive trace content was redacted. " : ""}{snapshot.truncated ? "Some captured content is truncated or unavailable." : ""}</p>}
    {snapshot.warnings.length > 0 && <ul className="space-y-1 text-[color:var(--rp-warning)]">{snapshot.warnings.map((warning, index) => <li key={index} className="break-words">{warning}</li>)}</ul>}
    <div><h4 className="mb-1 font-medium">Captured input</h4><pre className="max-h-36 overflow-auto whitespace-pre-wrap break-words text-xs">{snapshot.input === "" ? "(Explicit empty input)" : snapshot.input ?? "Unavailable"}</pre></div>
    <div><h4 className="mb-1 font-medium">Selected response</h4><pre className="max-h-44 overflow-auto whitespace-pre-wrap break-words text-xs">{snapshot.output.value === "" ? "(Explicit empty response)" : snapshot.output.value ?? "Unavailable"}</pre><p className="mt-1 text-[11px] text-[color:var(--rp-ink-muted)]">Selection: {snapshot.output.source === "agentRoot" ? "Agent root" : snapshot.output.source === "terminalGeneration" ? "Terminal generation" : snapshot.output.source === "selected" ? "Explicit response span" : "Unavailable"}. {snapshot.output.complete ? "Complete response." : "Response unavailable or incomplete."}</p>{snapshot.output.spanId && <Link className="mt-1 inline-block underline" to={`/runs/${encodeURIComponent(snapshot.runId)}/span/${encodeURIComponent(snapshot.output.spanId)}`}>View response span</Link>}</div>
    <dl className="grid grid-cols-2 gap-3">{[["Input tokens", measurement(metrics.inputTokens)], ["Output tokens", measurement(metrics.outputTokens)], ["Total tokens", measurement(metrics.totalTokens)], ["Duration", measurement(metrics.durationMs, " ms")], ["Reported cost", measurement(metrics.costUsd, " USD")], ["Tool calls", measurement(metrics.toolCalls)], ["Error spans", measurement(metrics.errorSpans)]].map(([label, value]) => <div key={label}><dt className="text-[color:var(--rp-ink-muted)]">{label}</dt><dd className="mt-1">{value}</dd></div>)}</dl>
    {snapshot.models.length > 0 && <details><summary className="cursor-pointer">Provider and model measurements</summary><ul className="mt-2 space-y-3">{snapshot.models.map((model, index) => <li key={index} className="break-words"><strong>{model.provider} / {model.model}</strong><p>{model.requests} requests · {measurement(model.errorSpans)} recorded errors</p><p>Input {measurement(model.inputTokens)} · Output {measurement(model.outputTokens)} · Cost {measurement(model.costUsd, " USD")}</p></li>)}</ul></details>}
    <Link className="inline-block underline" to={`/runs/${encodeURIComponent(snapshot.runId)}`}>Open captured run</Link>
  </section>;
}
