// AUTO-GENERATED by scripts/embed-migrations.ts. Do not edit by hand.
// Source of truth: drizzle/meta/_journal.json and drizzle/*.sql.
// Run `bun run db:generate` after changing src/db/schema.ts.

import migration0000Path from "../../drizzle/0000_massive_winter_soldier.sql" with { type: "file" };
import migration0001Path from "../../drizzle/0001_cynical_betty_brant.sql" with { type: "file" };
import migration0002Path from "../../drizzle/0002_flowery_shinobi_shaw.sql" with { type: "file" };
import migration0003Path from "../../drizzle/0003_span_identity_per_run.sql" with { type: "file" };
import migration0004Path from "../../drizzle/0004_spotty_thunderbolt.sql" with { type: "file" };
import migration0005Path from "../../drizzle/0005_sweet_smasher.sql" with { type: "file" };
import migration0006Path from "../../drizzle/0006_lying_proemial_gods.sql" with { type: "file" };

export const embeddedMigrationJournal = {
  "version": "7",
  "dialect": "sqlite",
  "entries": [
    {
      "idx": 0,
      "version": "6",
      "when": 1778475472563,
      "tag": "0000_massive_winter_soldier",
      "breakpoints": true
    },
    {
      "idx": 1,
      "version": "6",
      "when": 1778475541625,
      "tag": "0001_cynical_betty_brant",
      "breakpoints": true
    },
    {
      "idx": 2,
      "version": "6",
      "when": 1787429370282,
      "tag": "0002_flowery_shinobi_shaw",
      "breakpoints": true
    },
    {
      "idx": 3,
      "version": "6",
      "when": 1787429370283,
      "tag": "0003_span_identity_per_run",
      "breakpoints": true
    },
    {
      "idx": 4,
      "version": "6",
      "when": 1788822552935,
      "tag": "0004_spotty_thunderbolt",
      "breakpoints": true
    },
    {
      "idx": 5,
      "version": "6",
      "when": 1788823828928,
      "tag": "0005_sweet_smasher",
      "breakpoints": true
    },
    {
      "idx": 6,
      "version": "6",
      "when": 1788826316549,
      "tag": "0006_lying_proemial_gods",
      "breakpoints": true
    }
  ]
} as const;

export const embeddedMigrationFiles = [
  {
    relativePath: "0000_massive_winter_soldier.sql",
    sourcePath: migration0000Path,
  },
  {
    relativePath: "0001_cynical_betty_brant.sql",
    sourcePath: migration0001Path,
  },
  {
    relativePath: "0002_flowery_shinobi_shaw.sql",
    sourcePath: migration0002Path,
  },
  {
    relativePath: "0003_span_identity_per_run.sql",
    sourcePath: migration0003Path,
  },
  {
    relativePath: "0004_spotty_thunderbolt.sql",
    sourcePath: migration0004Path,
  },
  {
    relativePath: "0005_sweet_smasher.sql",
    sourcePath: migration0005Path,
  },
  {
    relativePath: "0006_lying_proemial_gods.sql",
    sourcePath: migration0006Path,
  },
] as const;
