/* eslint-disable -- Generated artifact; lint the browser TypeScript sources. */
// AUTO-GENERATED by scripts/build-verification-sdk.ts. Do not edit by hand.
// src/verification/protocol.ts
var PROTOCOL_VERSION = 1;
var VERIFICATION_LIMITS = {
  MAX_SESSIONS: 16,
  MAX_PENDING_PER_SESSION: 1,
  MAX_FRAME_BYTES: 128 * 1024,
  MAX_EVENT_BYTES: 16 * 1024,
  MAX_EVENTS: 1000,
  MAX_BUFFER_BYTES: 1024 * 1024,
  MAX_EVENT_AGE_MS: 60000,
  CREDENTIAL_TTL_MS: 60 * 60 * 1000,
  HELLO_TIMEOUT_MS: 3000,
  COMMAND_TIMEOUT_MS: 5000,
  CHECK_TIMEOUT_MS: 5000,
  QUIET_MS: 300,
  POLL_MS: 250,
  MAX_STEPS: 20,
  MAX_REPORTS: 1000,
  MAX_FLOWS: 100,
  MAX_EVIDENCE_EVENTS: 30,
  MAX_EVIDENCE_BYTES: 64 * 1024,
  MAX_CONTEXT_BYTES: 64 * 1024,
  MAX_REASON_LENGTH: 1000,
  MAX_SELECTOR_LENGTH: 1024,
  MAX_TEXT_LENGTH: 4096,
  MAX_NAME_LENGTH: 128,
  MAX_PREDICATE_DEPTH: 6,
  MAX_PREDICATE_NODES: 50
};

// src/verification/redaction.ts
var REDACTED_VALUE = "[REDACTED]";
var SENSITIVE_KEY = /password|passwd|passcode|secret|(?:(?:access|refresh|auth|bearer|api|id|session|csrf|client)[-_]?tokens?|(?:^|[-_])tokens?(?=$|[-_]))|session[-_]?id|(?:^|[-_])(?:sid|pwd|jwt)(?=$|[-_])|authorization|(?:^|[-_])(?:set[-_])?cookie(?=$|[-_])|api[-_]?key|access[-_]?key|private[-_]?key|client[-_]?secret|credit[-_]?card|card[-_]?number|cvv|cvc|ssn|(?:^|[-_])(?:signature|sig)$|(?:^|[-_])credential$|x-(?:amz|goog)-(?:signature|credential|security-token)$/i;
function defaultIsSensitiveKey(key) {
  return SENSITIVE_KEY.test(key);
}
var activePolicy;
function isSensitiveKey(key) {
  return activePolicy === undefined ? defaultIsSensitiveKey(key) : activePolicy.isSensitiveKey(key);
}
var SENSITIVE_PATH_SEGMENT = /^(reset|verify|verification|confirm|activate|invite|magic|magiclink|token|key|oauth|unsubscribe|password)$/i;
var PATH_TOKEN_MIN_LENGTH = 12;
function decodedUrlName(name) {
  try {
    return decodeURIComponent(name);
  } catch {
    return name;
  }
}
function redactUrl(raw, isSensitive = isSensitiveKey) {
  const hashStart = raw.indexOf("#");
  const hash = hashStart === -1 ? "" : raw.slice(hashStart);
  const beforeHash = hashStart === -1 ? raw : raw.slice(0, hashStart);
  const queryStart = beforeHash.indexOf("?");
  const pathPart = queryStart === -1 ? beforeHash : beforeHash.slice(0, queryStart);
  const query = queryStart === -1 ? "" : beforeHash.slice(queryStart + 1);
  let changed = false;
  let authority = pathPart;
  const userinfo = /^([a-z][a-z0-9+.-]*:\/\/)[^/]*@/i.exec(pathPart);
  if (userinfo !== null) {
    authority = `${userinfo[1] ?? ""}${REDACTED_VALUE}@${pathPart.slice(userinfo[0].length)}`;
    changed = true;
  }
  let newQuery = query;
  if (query !== "") {
    const params = new URLSearchParams(query);
    let queryChanged = false;
    for (const key of [...params.keys()]) {
      if (isSensitive(key)) {
        params.set(key, REDACTED_VALUE);
        queryChanged = true;
      }
    }
    if (queryChanged) {
      newQuery = params.toString();
      changed = true;
    }
  }
  const segments = authority.split("/");
  for (let i = 0;i + 1 < segments.length; i++) {
    const name = segments[i];
    const next = segments[i + 1];
    if (name !== undefined && next !== undefined && next.length >= PATH_TOKEN_MIN_LENGTH && SENSITIVE_PATH_SEGMENT.test(decodedUrlName(name))) {
      segments[i + 1] = REDACTED_VALUE;
      changed = true;
    }
  }
  let newHash = hash;
  if (hash.length > 1) {
    newHash = hash.replace(/(^|[#&?/])([A-Za-z0-9_.%-]+)=([^&\s]+)/g, (m, delimiter, key) => isSensitive(decodedUrlName(key)) ? `${delimiter}${key}=${REDACTED_VALUE}` : m);
    if (newHash !== hash)
      changed = true;
  }
  if (!changed)
    return raw;
  const queryOut = queryStart === -1 ? "" : `?${newQuery}`;
  return `${segments.join("/")}${queryOut}${newHash}`;
}
var KNOWN_SECRET = /eyJ[A-Za-z0-9_-]{4,}\.[A-Za-z0-9_-]{4,}\.[A-Za-z0-9_-]{4,}|(?:sk|rk)_(?:live|test)_[A-Za-z0-9]{10,}|sk-(?:ant|proj|svcacct|admin)-[A-Za-z0-9_-]{20,}|(?:AKIA|ASIA)[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{22,}|AIza[0-9A-Za-z_-]{35}|xox[baprs]-[A-Za-z0-9-]{10,}|ya29\.[A-Za-z0-9._-]{20,}/g;
function scrubKnownSecrets(text) {
  return text.replace(KNOWN_SECRET, REDACTED_VALUE);
}

// src/verification/serialization.ts
var TRANSPORT_LIMITS = {
  MAX_MESSAGE_BYTES: VERIFICATION_LIMITS.MAX_EVENT_BYTES,
  MAX_COLLECTION_ITEMS: 100,
  MAX_OBJECT_KEYS: 100,
  MAX_SERIALIZE_DEPTH: 8,
  MAX_ERROR_LENGTH: 1000,
  MAX_STRING_LENGTH: 4096
};
var TRUNCATED_VALUE = "[TRUNCATED]";
var UNSERIALIZABLE_VALUE = "[UNSERIALIZABLE]";
var OMIT_VALUE = Symbol("omit");
var MAX_KEY_LENGTH = 256;
var MAX_TOTAL_CHARACTERS = Math.floor(TRANSPORT_LIMITS.MAX_MESSAGE_BYTES / 4);
var MAX_TOTAL_NODES = TRANSPORT_LIMITS.MAX_COLLECTION_ITEMS * 5;
var mapEntries = Object.getOwnPropertyDescriptor(Map.prototype, "entries").value;
var mapSize = Reflect.get(Object.getOwnPropertyDescriptor(Map.prototype, "size"), "get");
var mapNext = Object.getPrototypeOf(new Map().entries()).next;
var setValues = Object.getOwnPropertyDescriptor(Set.prototype, "values").value;
var setSize = Reflect.get(Object.getOwnPropertyDescriptor(Set.prototype, "size"), "get");
var setNext = Object.getPrototypeOf(new Set().values()).next;
var typedArrayLength = Reflect.get(Object.getOwnPropertyDescriptor(Object.getPrototypeOf(Uint8Array.prototype), "length"), "get");
function scrubInput(value, state) {
  const scrubbed = state.scrubString ? state.scrubString(value) : value;
  if (typeof scrubbed !== "string")
    throw new TypeError("scrubString must return a string");
  if (scrubbed !== value)
    state.redacted = true;
  return scrubbed;
}
function boundedString(value, state, max) {
  const allowed = Math.max(0, Math.min(max, state.remainingCharacters));
  if (value.length <= allowed) {
    state.remainingCharacters -= value.length;
    return value;
  }
  state.truncatedValues += 1;
  const truncated = allowed <= TRUNCATED_VALUE.length ? TRUNCATED_VALUE.slice(0, allowed) : `${value.slice(0, allowed - TRUNCATED_VALUE.length)}${TRUNCATED_VALUE}`;
  state.remainingCharacters -= truncated.length;
  return truncated;
}
function sanitize(value, state, depth, key) {
  if (key !== undefined && (isSensitiveKey(key) || key === "urlRaw")) {
    state.redacted = true;
    return REDACTED_VALUE;
  }
  if (depth > TRANSPORT_LIMITS.MAX_SERIALIZE_DEPTH || state.nodes >= MAX_TOTAL_NODES) {
    state.truncatedValues += 1;
    return TRUNCATED_VALUE;
  }
  state.nodes += 1;
  if (value === null || typeof value === "boolean")
    return value;
  if (typeof value === "string") {
    const scrubbed = scrubInput(value, state);
    const scanned = scrubbed.slice(0, TRANSPORT_LIMITS.MAX_STRING_LENGTH * 4);
    if (scanned.length !== scrubbed.length)
      state.truncatedValues += 1;
    const redacted = redactText(scanned);
    if (redacted !== value)
      state.redacted = true;
    return boundedString(redacted, state, key?.toLowerCase() === "error" ? TRANSPORT_LIMITS.MAX_ERROR_LENGTH : TRANSPORT_LIMITS.MAX_STRING_LENGTH);
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value))
      state.truncatedValues += 1;
    return Number.isFinite(value) ? value : null;
  }
  if (typeof value === "bigint") {
    state.truncatedValues += 1;
    return value.toString();
  }
  if (typeof value === "undefined" || typeof value === "function" || typeof value === "symbol") {
    state.truncatedValues += 1;
    return OMIT_VALUE;
  }
  if (value instanceof Date) {
    state.truncatedValues += 1;
    return Number.isNaN(Date.prototype.getTime.call(value)) ? null : Date.prototype.toISOString.call(value);
  }
  if (value instanceof Map) {
    state.truncatedValues += 1;
    const out = Object.create(null);
    const entries = mapEntries.call(value);
    const total = mapSize.call(value);
    let n = 0;
    for (;; ) {
      if (state.nodes >= MAX_TOTAL_NODES || n >= TRANSPORT_LIMITS.MAX_COLLECTION_ITEMS) {
        state.droppedItems += total - n;
        break;
      }
      const entry = mapNext.call(entries);
      if (entry.done)
        break;
      const [k, v] = entry.value;
      if (typeof k !== "string") {
        state.truncatedValues += 1;
        state.droppedItems += 1;
        n += 1;
        continue;
      }
      const originalKey = k;
      if (["__proto__", "prototype", "constructor"].includes(originalKey)) {
        state.droppedItems += 1;
        n += 1;
        continue;
      }
      const redactedKey = redactText(scrubInput(originalKey, state).slice(0, 4096));
      if (redactedKey !== originalKey)
        state.redacted = true;
      const sk = boundedString(redactedKey, state, MAX_KEY_LENGTH);
      const sv = sanitize(v, state, depth + 1, sk);
      if (sv !== OMIT_VALUE)
        out[sk] = sv;
      n += 1;
    }
    return out;
  }
  if (value instanceof Set) {
    state.truncatedValues += 1;
    const out = [];
    const values = setValues.call(value);
    const total = setSize.call(value);
    let n = 0;
    for (;; ) {
      if (state.nodes >= MAX_TOTAL_NODES || n >= TRANSPORT_LIMITS.MAX_COLLECTION_ITEMS) {
        state.droppedItems += total - n;
        break;
      }
      const entry = setNext.call(values);
      if (entry.done)
        break;
      const sv = sanitize(entry.value, state, depth + 1);
      out.push(sv === OMIT_VALUE ? null : sv);
      n += 1;
    }
    return out;
  }
  if (ArrayBuffer.isView(value) && !(value instanceof DataView)) {
    state.truncatedValues += 1;
    const len = typedArrayLength.call(value);
    const out = [];
    let n = 0;
    for (;n < len; n += 1) {
      if (state.nodes >= MAX_TOTAL_NODES || n >= TRANSPORT_LIMITS.MAX_COLLECTION_ITEMS) {
        state.droppedItems += len - n;
        break;
      }
      const descriptor = Object.getOwnPropertyDescriptor(value, String(n));
      const item = descriptor && "value" in descriptor ? descriptor.value : undefined;
      if (typeof item !== "number" || !Number.isFinite(item)) {
        state.truncatedValues += 1;
        out.push(0);
      } else
        out.push(item);
      state.nodes += 1;
    }
    return out;
  }
  if (value instanceof Error) {
    state.truncatedValues += 1;
    const name = Object.getOwnPropertyDescriptor(value, "name");
    const message = Object.getOwnPropertyDescriptor(value, "message");
    return {
      name: sanitize(name ? "value" in name ? name.value : UNSERIALIZABLE_VALUE : "Error", state, depth + 1, "name"),
      message: sanitize(message && "value" in message ? message.value : UNSERIALIZABLE_VALUE, state, depth + 1, "error")
    };
  }
  if (!Array.isArray(value)) {
    const prototype = Object.getPrototypeOf(value);
    if (prototype !== null && prototype !== Object.prototype) {
      state.truncatedValues += 1;
      return UNSERIALIZABLE_VALUE;
    }
  }
  if (state.seen.has(value)) {
    state.truncatedValues += 1;
    return "[CIRCULAR]";
  }
  state.seen.add(value);
  try {
    if (Array.isArray(value)) {
      const out2 = [];
      const length = Object.getOwnPropertyDescriptor(value, "length")?.value;
      const considered = Math.min(length, TRANSPORT_LIMITS.MAX_COLLECTION_ITEMS);
      state.droppedItems += Math.max(0, length - considered);
      for (let index = 0;index < considered; index += 1) {
        if (state.nodes >= MAX_TOTAL_NODES) {
          state.droppedItems += 1;
          continue;
        }
        const descriptor = Object.getOwnPropertyDescriptor(value, String(index));
        if (!descriptor || !("value" in descriptor)) {
          state.truncatedValues += 1;
          out2.push(UNSERIALIZABLE_VALUE);
          continue;
        }
        const sanitized = sanitize(descriptor.value, state, depth + 1);
        if (state.nodes >= MAX_TOTAL_NODES) {
          state.droppedItems += 1;
          continue;
        }
        out2.push(sanitized === OMIT_VALUE ? null : sanitized);
      }
      return out2;
    }
    const out = Object.create(null);
    const allKeys = Object.keys(value);
    state.droppedItems += Object.getOwnPropertySymbols(value).length;
    const keys = allKeys.slice(0, TRANSPORT_LIMITS.MAX_OBJECT_KEYS);
    state.droppedItems += Math.max(0, allKeys.length - keys.length);
    const read = keys.map((key2) => {
      try {
        const descriptor = Object.getOwnPropertyDescriptor(value, key2);
        if (!descriptor || !("value" in descriptor))
          return { key: key2, value: undefined, scalar: true, ok: false };
        const v = descriptor.value;
        return { key: key2, value: v, scalar: v === null || typeof v !== "object", ok: true };
      } catch {
        return { key: key2, value: undefined, scalar: true, ok: false };
      }
    });
    for (const entry of [...read.filter((e) => e.scalar), ...read.filter((e) => !e.scalar)]) {
      if (["__proto__", "prototype", "constructor"].includes(entry.key)) {
        state.droppedItems += 1;
        continue;
      }
      const redactedKey = redactText(scrubInput(entry.key, state).slice(0, 4096));
      if (redactedKey !== entry.key)
        state.redacted = true;
      const safeKey = boundedString(redactedKey, state, MAX_KEY_LENGTH);
      if (!entry.ok) {
        state.truncatedValues += 1;
        out[safeKey] = UNSERIALIZABLE_VALUE;
        continue;
      }
      try {
        const sanitized = sanitize(entry.value, state, depth + 1, entry.key);
        if (sanitized !== OMIT_VALUE)
          out[safeKey] = sanitized;
      } catch {
        state.truncatedValues += 1;
        out[safeKey] = UNSERIALIZABLE_VALUE;
      }
    }
    return out;
  } finally {
    state.seen.delete(value);
  }
}
function sanitizeWithReport(value, options = {}) {
  const state = {
    seen: new WeakSet,
    remainingCharacters: MAX_TOTAL_CHARACTERS,
    nodes: 0,
    droppedItems: 0,
    truncatedValues: 0,
    redacted: false,
    scrubString: options.scrubString
  };
  let sanitized;
  try {
    sanitized = sanitize(value, state, 0);
  } catch {
    sanitized = UNSERIALIZABLE_VALUE;
    state.truncatedValues += 1;
  }
  const out = sanitized === OMIT_VALUE ? null : sanitized;
  const metadata = state.redacted ? { redacted: true } : {};
  if (state.droppedItems === 0 && state.truncatedValues === 0)
    return { value: out, ...metadata };
  const parts = [];
  if (state.droppedItems > 0)
    parts.push(`${state.droppedItems} item(s) dropped`);
  if (state.truncatedValues > 0)
    parts.push(`${state.truncatedValues} value(s) truncated`);
  return {
    value: out,
    ...metadata,
    truncation: {
      droppedItems: state.droppedItems,
      truncatedValues: state.truncatedValues,
      note: `partial — ${parts.join(", ")}; this is NOT the whole value. Scope the read with \`path\`/\`depth\` to see the rest.`
    }
  };
}
function redactText(text) {
  return scrubKnownSecrets(text).replace(/\bauthorization["']?\s*[:=]\s*["']?(?:bearer|basic)\s+[^\s"'&,;}]+/gi, `authorization: ${REDACTED_VALUE}`).replace(/\b(Bearer|Basic)\s+(?=[A-Za-z0-9._~+/=-]{16,})(?=[A-Za-z0-9._~+/=-]*[\d._~+/=-])[A-Za-z0-9._~+/=-]+/gi, (_match, scheme) => `${scheme} ${REDACTED_VALUE}`).replace(/https?:\/\/[^\s<>"']+/gi, (url) => redactUrl(url)).replace(/(^|[\s?&#,;{"'])([A-Za-z][A-Za-z0-9_.-]{0,127})(\s*[=:]\s*["']?)([^&\s,;"'}]+)/g, (match, prefix, key, separator) => isSensitiveKey(key) ? `${prefix}${key}${separator}${REDACTED_VALUE}` : match);
}

// src/verification/validation.ts
class VerificationInputError extends Error {
  status = 400;
  constructor(message) {
    super(message.slice(0, VERIFICATION_LIMITS.MAX_REASON_LENGTH));
    this.name = "VerificationInputError";
  }
}
var forbiddenKeys = new Set(["__proto__", "prototype", "constructor"]);
function invalid(message) {
  throw new VerificationInputError(message);
}
function record(value, label) {
  if (value === null || typeof value !== "object" || Array.isArray(value))
    return invalid(`${label} must be an object`);
  const proto = Object.getPrototypeOf(value);
  if (proto !== null && proto !== Object.prototype)
    return invalid(`${label} must be a plain object`);
  for (const key of Reflect.ownKeys(value)) {
    if (typeof key !== "string" || forbiddenKeys.has(key))
      return invalid(`${label} contains an unsupported key`);
    const descriptor = Object.getOwnPropertyDescriptor(value, key);
    if (!descriptor || !("value" in descriptor))
      return invalid(`${label} cannot contain accessors`);
  }
  return value;
}
function keys(value, allowed, label) {
  for (const key of Object.keys(value))
    if (!allowed.includes(key))
      invalid(`${label} has unsupported field ${key}`);
}
function text(value, label, max = VERIFICATION_LIMITS.MAX_TEXT_LENGTH, empty = false) {
  if (typeof value !== "string" || value.length > max || !empty && value.trim().length === 0 || value.includes(String.fromCharCode(0))) {
    return invalid(`${label} must be ${empty ? "a" : "a nonempty"} string of at most ${max} characters`);
  }
  return value;
}
function optionalString(obj, key, max) {
  return Object.hasOwn(obj, key) ? text(obj[key], key, max) : undefined;
}
function validateOrigin(value) {
  const raw = text(value, "origin", VERIFICATION_LIMITS.MAX_TEXT_LENGTH);
  let url;
  try {
    url = new URL(raw);
  } catch {
    return invalid("origin must be a loopback HTTP(S) origin");
  }
  if (!["http:", "https:"].includes(url.protocol) || !["localhost", "127.0.0.1", "[::1]"].includes(url.hostname) || url.username || url.password || url.pathname !== "/" || url.search || url.hash) {
    return invalid("origin must be a loopback HTTP(S) origin without credentials, path, query or fragment");
  }
  return url.origin;
}
function parseCommand(value) {
  const obj = record(value, "command");
  switch (obj.type) {
    case "snapshot": {
      keys(obj, ["type", "selector"], "snapshot command");
      const selector = optionalString(obj, "selector", VERIFICATION_LIMITS.MAX_SELECTOR_LENGTH);
      return selector === undefined ? { type: "snapshot" } : { type: "snapshot", selector };
    }
    case "click":
      keys(obj, ["type", "selector"], "click command");
      return { type: "click", selector: text(obj.selector, "selector", VERIFICATION_LIMITS.MAX_SELECTOR_LENGTH) };
    case "fill":
      keys(obj, ["type", "selector", "value"], "fill command");
      return { type: "fill", selector: text(obj.selector, "selector", VERIFICATION_LIMITS.MAX_SELECTOR_LENGTH), value: text(obj.value, "fill value", VERIFICATION_LIMITS.MAX_TEXT_LENGTH, true) };
    case "state":
      keys(obj, ["type", "store"], "state command");
      return { type: "state", store: text(obj.store, "store", VERIFICATION_LIMITS.MAX_NAME_LENGTH) };
    default:
      return invalid("unsupported command type");
  }
}

// src/verification/browser/patching/capture-method.ts
function captureMethod(target, key) {
  return target[key];
}
function captureValueSetter(proto) {
  const descriptor = Object.getOwnPropertyDescriptor(proto, "value");
  if (descriptor === undefined)
    return;
  const setter = captureMethod(descriptor, "set");
  return setter;
}

// src/verification/browser/observers/types.ts
function observeSafely(observation, onError) {
  try {
    observation();
  } catch {
    try {
      onError?.();
    } catch {}
  }
}
function observerFailure(emit, observer) {
  return () => emit("observer.error", { observer, message: "Observation could not be captured completely" });
}

// src/verification/browser/observers/console.ts
function stringifyArgs(args, sanitize2) {
  let truncated = args.length > 100;
  const message = args.slice(0, 100).map((arg) => {
    const safe = sanitize2(arg instanceof Error ? arg.message : arg);
    truncated ||= safe.truncated;
    return typeof safe.value === "string" ? safe.value : JSON.stringify(safe.value);
  }).join(" ");
  return { message, truncated };
}
function installConsole(emit, sanitize2 = (value) => {
  const safe = sanitizeWithReport(value);
  return { value: safe.value, truncated: Boolean(safe.truncation || safe.redacted) };
}) {
  const methods = ["log", "warn", "error", "info", "debug"];
  const originals = new Map;
  const patched = new Map;
  let active = true;
  const failure = observerFailure(emit, "console");
  const onError = (event) => observeSafely(() => {
    if (active)
      emit("console", { level: "error", message: event.message });
  }, failure);
  const onRejection = (event) => observeSafely(() => {
    const message = stringifyArgs([event.reason], sanitize2);
    if (active)
      emit("console", { level: "error", message: message.message }, undefined, message.truncated);
  }, failure);
  const teardown = () => {
    active = false;
    for (const [method, original] of originals) {
      if (console[method] === patched.get(method))
        console[method] = original;
    }
    window.removeEventListener("error", onError);
    window.removeEventListener("unhandledrejection", onRejection);
  };
  try {
    for (const method of methods) {
      const original = captureMethod(console, method);
      originals.set(method, original);
      const callOriginal = original.bind(console);
      const wrapper = (...args) => {
        observeSafely(() => {
          if (active) {
            const message = stringifyArgs(args, sanitize2);
            emit("console", { level: method, message: message.message }, undefined, message.truncated);
          }
        }, failure);
        callOriginal(...args);
      };
      patched.set(method, wrapper);
      console[method] = wrapper;
    }
    window.addEventListener("error", onError);
    window.addEventListener("unhandledrejection", onRejection);
  } catch (error) {
    observeSafely(teardown);
    throw error;
  }
  return teardown;
}

// src/verification/browser/observers/network.ts
function statusIsOk(status) {
  return status >= 200 && status < 400;
}
function urlOf(input) {
  if (typeof input === "string")
    return input;
  if (input instanceof URL)
    return input.href;
  return input.url;
}
function methodOf(input, init) {
  if (init?.method !== undefined)
    return init.method.toUpperCase();
  if (input instanceof Request)
    return input.method.toUpperCase();
  return "GET";
}
function installNetwork(emit, getActionId) {
  const origFetch = captureMethod(window, "fetch");
  const callFetch = origFetch.bind(window);
  const proto = XMLHttpRequest.prototype;
  const origOpen = captureMethod(proto, "open");
  const origSend = captureMethod(proto, "send");
  const callOpen = origOpen;
  let active = true;
  let sequence = 0;
  const failure = observerFailure(emit, "network");
  const makeMeta = (url, method) => ({
    requestId: `n${++sequence}`,
    method,
    url: redactUrl(new URL(url, location.href).href),
    start: performance.now(),
    actionId: getActionId()
  });
  const start = (meta2, initiator) => {
    if (active)
      emit("network.start", {
        requestId: meta2.requestId,
        url: meta2.url,
        method: meta2.method,
        initiator
      }, meta2.actionId ?? null);
  };
  const finish = (meta2, initiator, status) => {
    if (active)
      emit("network", {
        requestId: meta2.requestId,
        url: meta2.url,
        method: meta2.method,
        status,
        ok: statusIsOk(status),
        durationMs: Math.max(0, Math.round(performance.now() - meta2.start)),
        initiator
      }, meta2.actionId ?? null);
  };
  const patchedFetch = (input, init) => {
    if (!active)
      return callFetch(input, init);
    let meta2;
    observeSafely(() => {
      meta2 = makeMeta(urlOf(input), methodOf(input, init));
      start(meta2, "fetch");
    }, failure);
    let result;
    try {
      result = callFetch(input, init);
    } catch (error) {
      observeSafely(() => {
        if (meta2)
          finish(meta2, "fetch", 0);
      }, failure);
      throw error;
    }
    return result.then((response) => {
      observeSafely(() => {
        if (meta2)
          finish(meta2, "fetch", response.status);
      }, failure);
      return response;
    }, (error) => {
      observeSafely(() => {
        if (meta2)
          finish(meta2, "fetch", 0);
      }, failure);
      throw error;
    });
  };
  const meta = new WeakMap;
  const pending = new Map;
  const patchedOpen = function(method, url, ...rest) {
    callOpen.call(this, method, url, ...rest);
    observeSafely(() => {
      if (active)
        meta.set(this, { method: method.toUpperCase(), url: String(url) });
    }, failure);
  };
  const patchedSend = function(body) {
    let cleanup;
    let request;
    observeSafely(() => {
      if (!active || pending.has(this))
        return;
      const source = meta.get(this);
      if (!source) {
        failure();
        return;
      }
      if (pending.size >= 1000) {
        failure();
        return;
      }
      request = makeMeta(source.url, source.method);
      const current = request;
      const onLoadEnd = () => {
        cleanup?.();
        observeSafely(() => finish(current, "xhr", this.status), failure);
      };
      cleanup = () => {
        this.removeEventListener("loadend", onLoadEnd);
        pending.delete(this);
      };
      this.addEventListener("loadend", onLoadEnd);
      pending.set(this, cleanup);
      start(current, "xhr");
    }, failure);
    try {
      origSend.call(this, body ?? null);
    } catch (error) {
      observeSafely(() => {
        cleanup?.();
        if (request)
          finish(request, "xhr", 0);
      }, failure);
      throw error;
    }
  };
  const teardown = () => {
    active = false;
    if (window.fetch === patchedFetch)
      window.fetch = origFetch;
    if (proto.open === patchedOpen)
      proto.open = origOpen;
    if (proto.send === patchedSend)
      proto.send = origSend;
    for (const cleanup of pending.values())
      observeSafely(cleanup);
    pending.clear();
  };
  try {
    window.fetch = patchedFetch;
    proto.open = patchedOpen;
    proto.send = patchedSend;
  } catch (error) {
    observeSafely(teardown);
    throw error;
  }
  return teardown;
}

// src/verification/browser/observers/route.ts
function installRoute(emit) {
  const origPush = captureMethod(history, "pushState");
  const origReplace = captureMethod(history, "replaceState");
  const callPush = origPush.bind(history);
  const callReplace = origReplace.bind(history);
  let active = true;
  let lastHref = location.href;
  const failure = observerFailure(emit, "route");
  const fire = () => observeSafely(() => {
    if (!active || location.href === lastHref)
      return;
    lastHref = location.href;
    emit("route", { url: redactUrl(lastHref) });
  }, failure);
  const patchedPush = (data, unused, url) => {
    callPush(data, unused, url);
    fire();
  };
  const patchedReplace = (data, unused, url) => {
    callReplace(data, unused, url);
    fire();
  };
  const teardown = () => {
    active = false;
    if (history.pushState === patchedPush)
      history.pushState = origPush;
    if (history.replaceState === patchedReplace)
      history.replaceState = origReplace;
    window.removeEventListener("popstate", fire);
    window.removeEventListener("hashchange", fire);
  };
  try {
    history.pushState = patchedPush;
    history.replaceState = patchedReplace;
    window.addEventListener("popstate", fire);
    window.addEventListener("hashchange", fire);
  } catch (error) {
    observeSafely(teardown);
    throw error;
  }
  return teardown;
}

// src/verification/browser/dom/realm.ts
function ctorIn(node, name) {
  if (node === null || typeof node !== "object")
    return;
  const doc = node.ownerDocument ?? node;
  const view = doc.defaultView;
  if (view === null || view === undefined)
    return;
  return view[name];
}
function isIn(node, name, ambient) {
  const ctor = ctorIn(node, name) ?? ambient;
  return typeof ctor === "function" && node instanceof ctor;
}
var isHtmlElement = (n) => isIn(n, "HTMLElement", typeof HTMLElement === "undefined" ? undefined : HTMLElement);
var isInput = (n) => isIn(n, "HTMLInputElement", typeof HTMLInputElement === "undefined" ? undefined : HTMLInputElement);
var isTextArea = (n) => isIn(n, "HTMLTextAreaElement", typeof HTMLTextAreaElement === "undefined" ? undefined : HTMLTextAreaElement);
function valuePrototypeOf(el) {
  const name = isTextArea(el) ? "HTMLTextAreaElement" : "HTMLInputElement";
  const ctor = ctorIn(el, name);
  if (typeof ctor !== "function")
    return;
  const proto = ctor.prototype;
  return typeof proto === "object" && proto !== null ? proto : undefined;
}

// src/verification/browser/actions/value-input.ts
function setNativeValue(el, value) {
  const proto = valuePrototypeOf(el);
  const setter = proto === undefined ? undefined : captureValueSetter(proto);
  if (setter !== undefined) {
    setter.call(el, value);
  } else {
    el.value = value;
  }
  const notPrevented = el.dispatchEvent(new Event("input", { bubbles: true, cancelable: true }));
  el.dispatchEvent(new Event("change", { bubbles: true }));
  return !notPrevented;
}
function assertNotRichText(el, action) {
  const flag = el.getAttribute("contenteditable");
  if (el.isContentEditable || flag !== null && flag !== "false") {
    throw new Error(`cannot ${action} a contenteditable element — rich-text editors keep their own document model, ` + "so writing to the DOM here would look right and submit the old content. This surface is not supported yet.");
  }
}
function assertEditable(el, action) {
  if (el.disabled) {
    throw new Error(`cannot ${action} a disabled <${el.tagName.toLowerCase()}> — a user could not edit it, so forcing the value would put the app in a state nobody can reach`);
  }
  if (el.readOnly) {
    throw new Error(`cannot ${action} a readonly <${el.tagName.toLowerCase()}> — a user could not edit it, so forcing the value would put the app in a state nobody can reach`);
  }
}

// src/verification/browser/actions/index.ts
function matches(selector) {
  try {
    return document.querySelectorAll(selector);
  } catch {
    throw new Error("Invalid CSS selector");
  }
}
function actionTarget(selector) {
  const elements = matches(selector);
  if (!elements.length)
    throw new Error("Selector did not match an element");
  if (elements.length !== 1)
    throw new Error("Selector matched multiple elements; use a unique selector");
  const element = elements[0];
  if (!isHtmlElement(element))
    throw new Error("Actions require an HTML element");
  if (element.matches(":disabled") || element.getAttribute("aria-disabled") === "true") {
    throw new Error("Cannot act on a disabled element");
  }
  if (element.closest("[inert]"))
    throw new Error("Cannot act on an inert element");
  const style = window.getComputedStyle(element);
  if (!element.getClientRects().length || style.visibility !== "visible" || style.display === "none") {
    throw new Error("Cannot act on a hidden element");
  }
  return element;
}
function runDomCommand(command, sanitize2 = (value) => {
  const safe = sanitizeWithReport(value);
  return { value: safe.value, truncated: Boolean(safe.truncation || safe.redacted) };
}) {
  if (command.type === "snapshot") {
    const selector = command.selector ?? "button,input,textarea,select,a,[role]";
    const elements = matches(selector);
    if (command.selector) {
      const safe = sanitize2(selector);
      return { result: { selector: safe.value, count: elements.length }, truncated: safe.truncated };
    }
    let truncated = elements.length > 100;
    const summaries = Array.from(elements).slice(0, 100).map((element2) => {
      const label = element2.getAttribute("aria-label") ?? (isInput(element2) || isTextArea(element2) ? "" : element2.textContent ?? "");
      const safe = sanitize2(label);
      const safeLabel = typeof safe.value === "string" ? safe.value : "";
      const safeId = sanitize2(element2.id);
      const safeRole = sanitize2(element2.getAttribute("role"));
      if (safe.truncated || safeId.truncated || safeRole.truncated || safeLabel.length > 240)
        truncated = true;
      return {
        tag: element2.tagName.toLowerCase(),
        id: safeId.value,
        role: safeRole.value,
        label: safeLabel.slice(0, 240),
        disabled: element2.matches(":disabled") || element2.getAttribute("aria-disabled") === "true"
      };
    });
    return { result: { selector, count: elements.length, elements: summaries }, truncated };
  }
  const element = actionTarget(command.selector);
  if (command.type === "click") {
    element.click();
    return { result: { dispatched: true } };
  }
  assertNotRichText(element, "fill");
  if (!isInput(element) && !isTextArea(element))
    throw new Error("Fill requires an input or textarea");
  if (isInput(element) && !["text", "search", "tel", "url", "email", "password", "number"].includes(element.type)) {
    throw new Error("This input type does not support text filling");
  }
  assertEditable(element, "fill");
  element.focus();
  const prevented = setNativeValue(element, command.value);
  return { result: { dispatched: true, defaultPrevented: prevented } };
}

// src/verification/browser/index.ts
var ACTIVE_RUNTIME = Symbol.for("runphantom.verification.active");
var encoder = new TextEncoder;
function nameValid(value) {
  return typeof value === "string" && /^[A-Za-z0-9_.:-]{1,128}$/.test(value);
}
function connect(options) {
  validateOrigin(location.origin);
  const origin = validateOrigin(options.url);
  if (!nameValid(options.sessionId))
    throw new Error("Invalid verification session ID");
  if (typeof options.token !== "string" || !options.token || options.token.length > 512) {
    throw new Error("Invalid verification session token");
  }
  const globals = window;
  if (globals[ACTIVE_RUNTIME])
    throw new Error("A Run Phantom verification runtime is already connected on this page");
  const lease = {};
  globals[ACTIVE_RUNTIME] = lease;
  const socketUrl = new URL("/verification/ws", origin);
  socketUrl.protocol = socketUrl.protocol === "https:" ? "wss:" : "ws:";
  socketUrl.searchParams.set("sessionId", options.sessionId);
  let socket;
  try {
    socket = new WebSocket(socketUrl);
  } catch (error) {
    delete globals[ACTIVE_RUNTIME];
    throw error;
  }
  const stores = new Map;
  const teardown = [];
  const coverage = { network: false, console: false, route: false, dom: true, state: true, signal: true };
  const secrets = new Set([options.token]);
  const secretSpellings = new Set([options.token]);
  const rememberSpelling = (value) => {
    secretSpellings.add(value);
    try {
      secretSpellings.add(encodeURIComponent(value));
    } catch {}
  };
  rememberSpelling(options.token);
  let secretCharacters = options.token.length;
  let active = true;
  let ready = false;
  let currentActionId;
  let sending = false;
  const earlyEvents = [];
  let earlyBytes = 0;
  const prepare = (value) => {
    const scrubString = (text2) => {
      let result = text2;
      for (const spelling of secretSpellings) {
        if (result === spelling || spelling.length >= 4 && result.includes(spelling)) {
          result = result.split(spelling).join("[REDACTED]");
        }
      }
      return result;
    };
    const safe = sanitizeWithReport(value, { scrubString });
    const encoded = JSON.stringify(safe.value);
    return {
      value: safe.value,
      truncated: Boolean(safe.truncation || safe.redacted || /\[(?:TRUNCATED|UNSERIALIZABLE|REDACTED|CIRCULAR)\]/.test(encoded))
    };
  };
  const send = (message) => {
    if (!active || socket.readyState !== WebSocket.OPEN)
      return false;
    const text2 = JSON.stringify(message);
    if (encoder.encode(text2).byteLength > VERIFICATION_LIMITS.MAX_FRAME_BYTES)
      return false;
    socket.send(text2);
    return true;
  };
  const prepareEvent = (type, data) => {
    const fields = type === "console" ? ["message", "stack"] : type === "network" || type === "network.start" ? ["url", "error"] : type === "route" ? ["url"] : type === "signal" ? ["data"] : type === "observer.error" ? ["message"] : [];
    const value = {};
    let truncated = false;
    for (const [field, item] of Object.entries(data)) {
      if (fields.includes(field)) {
        const safe = prepare(item);
        value[field] = safe.value;
        truncated ||= safe.truncated;
      } else {
        const safe = sanitizeWithReport(item);
        value[field] = safe.value;
        truncated ||= Boolean(safe.truncation || safe.redacted);
      }
    }
    return { value, truncated };
  };
  const emit = (type, data, actionId = currentActionId, truncated = false) => observeSafely(() => {
    if (!active)
      return;
    if (sending || socket.bufferedAmount > VERIFICATION_LIMITS.MAX_FRAME_BYTES * 2) {
      disconnect();
      return;
    }
    sending = true;
    try {
      const safe = prepareEvent(type, data);
      const event = { type, data: safe.value, ...actionId ? { actionId } : {}, ...safe.truncated || truncated ? { truncated: true } : {} };
      const bytes = encoder.encode(JSON.stringify(event)).byteLength;
      if (bytes > VERIFICATION_LIMITS.MAX_EVENT_BYTES) {
        disconnect();
        return;
      }
      const message = { type: "event", event };
      if (!ready) {
        if (earlyEvents.length >= 100 || earlyBytes + bytes > VERIFICATION_LIMITS.MAX_FRAME_BYTES) {
          disconnect();
          return;
        }
        earlyEvents.push(message);
        earlyBytes += bytes;
      } else if (!send(message))
        disconnect();
    } finally {
      sending = false;
    }
  }, () => disconnect());
  const disconnect = () => {
    if (!active)
      return;
    active = false;
    ready = false;
    clearTimeout(handshakeTimer);
    for (const cleanup of teardown.reverse())
      observeSafely(cleanup);
    teardown.length = 0;
    stores.clear();
    secrets.clear();
    secretSpellings.clear();
    earlyEvents.length = 0;
    socket.removeEventListener("open", onOpen);
    socket.removeEventListener("message", onMessage);
    socket.removeEventListener("close", disconnect);
    socket.removeEventListener("error", disconnect);
    observeSafely(() => socket.close(1000, "Runtime disconnected"));
    if (globals[ACTIVE_RUNTIME] === lease)
      delete globals[ACTIVE_RUNTIME];
  };
  const handshakeTimer = setTimeout(disconnect, VERIFICATION_LIMITS.HELLO_TIMEOUT_MS + 3000);
  const install = (name, callback) => {
    try {
      teardown.push(callback());
      coverage[name] = true;
    } catch {
      coverage[name] = false;
    }
  };
  const onOpen = () => {
    if (!active)
      return;
    install("console", () => installConsole(emit, prepare));
    install("network", () => installNetwork(emit, () => currentActionId));
    install("route", () => installRoute(emit));
    observeSafely(() => send({ type: "hello", version: PROTOCOL_VERSION, token: options.token, coverage }), disconnect);
  };
  const act = (id, command) => {
    try {
      if (command.type === "fill" && command.value && !secrets.has(command.value)) {
        if (secretCharacters + command.value.length > 1024 * 1024 || secrets.size >= 1000) {
          throw new Error("Live fill redaction capacity reached; reconnect before another fill");
        }
        secrets.add(command.value);
        rememberSpelling(command.value);
        secretCharacters += command.value.length;
      }
      if (command.type === "click" || command.type === "fill") {
        currentActionId = id;
        emit("action.boundary", {}, id);
        if (!active || !ready)
          throw new Error("Verification disconnected before action dispatch");
      }
      let output;
      if (command.type === "state") {
        const read = stores.get(command.store);
        if (!read)
          throw new Error("Requested store is not registered");
        const safe2 = prepare(read());
        const store = sanitizeWithReport(command.store);
        output = { result: { store: store.value, value: safe2.value }, truncated: Boolean(safe2.truncated || store.truncation || store.redacted) };
      } else
        output = runDomCommand(command, prepare);
      const safe = command.type === "state" ? { value: output.result } : sanitizeWithReport(output.result);
      if (!send({ type: "result", id, ok: true, result: safe.value, ...output.truncated || safe.truncation || safe.redacted ? { truncated: true } : {} }))
        disconnect();
    } catch (error) {
      const safe = prepare(error instanceof Error ? error.message : "Runtime command failed");
      send({ type: "result", id, ok: false, error: String(safe.value).slice(0, 1000) });
    }
  };
  const onMessage = (event) => {
    try {
      if (typeof event.data !== "string" || encoder.encode(event.data).byteLength > VERIFICATION_LIMITS.MAX_FRAME_BYTES) {
        disconnect();
        return;
      }
      const message = JSON.parse(event.data);
      if (!message || typeof message !== "object" || Array.isArray(message)) {
        disconnect();
        return;
      }
      if (message.type === "ready" && Object.keys(message).length === 1 && !ready) {
        ready = true;
        clearTimeout(handshakeTimer);
        for (const queued of earlyEvents)
          if (!send(queued)) {
            disconnect();
            return;
          }
        earlyEvents.length = 0;
        earlyBytes = 0;
        return;
      }
      if (!ready || message.type !== "command" || !nameValid(message.id) || Object.keys(message).some((key) => !["type", "id", "command"].includes(key))) {
        disconnect();
        return;
      }
      const command = parseCommand(message.command);
      act(message.id, command);
    } catch {
      disconnect();
    }
  };
  socket.addEventListener("open", onOpen);
  socket.addEventListener("message", onMessage);
  socket.addEventListener("close", disconnect);
  socket.addEventListener("error", disconnect);
  return {
    disconnect,
    signal(name, data) {
      if (!active)
        throw new Error("Verification runtime is disconnected");
      if (!nameValid(name))
        throw new Error("Signal name must be 1–128 letters, digits or ._:-");
      emit("signal", { name, ...data === undefined ? {} : { data } });
    },
    registerStore(name, read) {
      if (!active)
        throw new Error("Verification runtime is disconnected");
      if (!nameValid(name) || typeof read !== "function")
        throw new Error("A valid store name and reader function are required");
      if (stores.has(name))
        throw new Error("Store name is already registered");
      if (stores.size >= 100)
        throw new Error("Registered store limit reached");
      stores.set(name, read);
      return () => {
        if (stores.get(name) === read)
          stores.delete(name);
      };
    }
  };
}
export {
  connect
};
