#!/usr/bin/env bun
/** Generate/check the deterministic ESM asset embedded by source and compiled daemons. */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dir, "..");
const output = path.join(root, "src/verification/browser-sdk.js");
const arguments_ = process.argv.slice(2);
if (arguments_.some((arg) => arg !== "--check")) throw new Error("Usage: bun scripts/build-verification-sdk.ts [--check]");
const result = await Bun.build({
  entrypoints: [path.join(root, "src/verification/browser/index.ts")],
  root, target: "browser", format: "esm", minify: false, sourcemap: "none",
});
if (!result.success || result.outputs.length !== 1) {
  throw new Error(`Browser SDK build failed: ${result.logs.map(String).join("\n")}`);
}
const source = [
  "/* eslint-disable -- Generated artifact; lint the browser TypeScript sources. */",
  "// AUTO-GENERATED by scripts/build-verification-sdk.ts. Do not edit by hand.",
  await result.outputs[0].text(),
].join("\n");
if (arguments_.includes("--check")) {
  if (!existsSync(output) || readFileSync(output, "utf8") !== source) {
    throw new Error("Browser SDK bundle is stale. Run bun scripts/build-verification-sdk.ts");
  }
  console.log("[verification-sdk] Generated browser bundle is up to date");
} else {
  writeFileSync(output, source);
  console.log("[verification-sdk] Generated browser bundle");
}
